### ISSUE TITLE
Gradient save issue

### ISSUE THREAD

**Issue by 4SaltyInPadella** [SilenceLeo/snowb-bmf#16]
Hi,I have encountered an issue with gradients with both fill and stroke options.
If i set more than two colors in a single gradient and save it as sbf positions are set to 0

Original Project

![before](https://user-images.githubusercontent.com/48244706/121554204-3dcd0300-ca12-11eb-9f5e-0e18ab9f3fc1.JPG)

After Save -> .sbf -> Open

![after](https://user-images.githubusercontent.com/48244706/121554210-402f5d00-ca12-11eb-8311-591196b9beed.JPG)

Great job with the tool by the way, we love it! :)

**Comment by SilenceLeo** [comment]
Hey, thanks for reaching out.  I will check whats up and fix it as soon as possible.

**Comment by SilenceLeo** [comment]
@4SaltyInPadella 
It is fixed now.  But for old files you will have to adjust the gradient again to fix it there too.
