### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by yangbo1024** [SilenceLeo/snowb-bmf#18]
👍
1. Padding split to x-padding, y-padding.
2. Shadow with Stroke effect is not correct(eg.  Solid stroke 5px, Shadow offset x 2px, offset y 2px).
3. Need Batching.
4. Need API Doc.
5. Kerning map.

首先，点赞~
1.Padding拆分为x和y单独padding；
2.阴影和描边同时使用时，效果不对，看起来怪怪的，像被截断；而且边缘变得很硬，像是方形而不是轮廓；
比如描边5像素，阴影xy各2像素。
3.缺少批处理功能或者接口；
4.缺少API文档。
5. Kerning字偶距信息编辑。

**Comment by SilenceLeo** [comment]
@yangbo1024 

1.Padding拆分为x和y单独padding；
当时为了方便操作，合并了xy，我会考虑改回拆分模式。

3.缺少批处理功能或者接口；
这个可以说一下使用场景吗？

4.缺少API文档。
你是说的类似使用手册吗？

5.Kerning字偶距信息编辑。
Kerning 编辑是有的。

    1. preview 模式
    2. 点击某个字符
    3. 调整这两个相邻字符的 Kerning

![Kerning 编辑](https://user-images.githubusercontent.com/4632034/123031556-064d5600-d417-11eb-9dd1-d7839ea58126.png)

**Comment by yangbo1024** [comment]
好的。
3. 大量不同字体使用的时候需要用到批处理来应对频繁增减字符的高频操作；实际例子就是个人的小项目里面已经用到了12套字体。
4. API文档这个主要是方便做扩展，比如上述的批处理可以在有API的情况下自己实现（比如用electron打包成原生引用）。
5. 是这样的，貌似没有默认读取字体kerning map；单文字编辑这个我发现了，放到preview里有点迷惑，以为只是个预览；这个从0开始逐对编辑比较麻烦，可能只适合微调。所以是否可以考虑做成默认读取kerning信息，在此基础上编辑pair列表。

请问方便给个QQ微信等IM的联系方式吗，邮箱yangbo1024@qq.com

**Comment by SilenceLeo** [comment]
@yangbo1024 
Kering map 确实在内部已经加载，工具中也确实是微调，会合并计算。
已经邮件发你我的微信。
