### ISSUE TITLE
功能请求：设置图片宽高

### ISSUE THREAD

**Issue by panli32811** [SilenceLeo/snowb-bmf#2]
有时候并不想使用自动宽高，手动设置宽高的功能应该还是需要的

**Comment by SilenceLeo** [comment]
我在考虑如何实现这个界面交互比较好， @panli32811 你有好的建议吗？

**Comment by panli32811** [comment]
![image](https://user-images.githubusercontent.com/8217836/99946527-775d5a00-2db1-11eb-9a87-57a65c206954.png)

这是我看ubfg的界面，可以参考下

**Comment by SilenceLeo** [comment]
已增强设置纹理尺寸。
取消自动打包后，可以设置最大宽高，会优化空白区域。
设置固定尺寸之后，将固定纹理尺寸，不做优化。

固定尺寸适合 Power of 2。例如设置为 256 * 256，512 * 512 。

![image](https://user-images.githubusercontent.com/4632034/103419857-bf9d4280-4bcf-11eb-99c1-830c3849291f.png)
