### ISSUE TITLE
Fallback font support

### ISSUE THREAD

**Issue by SBCGames** [SilenceLeo/snowb-bmf#21]
I just came accross your app and it looks very promising!

In past I used Littera and they have very useful feature - fallback font. If glyph X is not present in selected font, it looks in fallback font for it:
![obrazek](https://user-images.githubusercontent.com/8962889/133001269-8e5f358b-c8c0-4ff7-80d6-e3537cb188e0.png)

What it is good for? I work on games and we do localization into many languages. I used it to mix cyrillic or CJK characters from different .ttf files into single texture atlas.

In fact, Littera has one fallback font. It would be the best if you could stack multiple source font files. Then you would use glyph from the first one in which it is defined.

**Comment by SilenceLeo** [comment]
Hi,

If you encounter any problems in use, please feedback to me.

Thanks!

**Comment by SBCGames** [comment]
Thanks a lot! 👍
