### ISSUE TITLE
Blurry pixel font output

### ISSUE THREAD

**Issue by Silver-Streak** [SilenceLeo/snowb-bmf#26]
Hello! I'm testing out snowb-bmf and am really impressed with the functionality.

I am primarily looking at it for game dev purposes, where I primarily need to use pixel fonts.

For some reason, all of the fonts I output have a bit of subpixel blur outside of the text lines. Is there an option to disable that or antialiasing?

As an example, here is the Monogram font (https://datagoblin.itch.io/monogram) exported using Angelcode BMFont's most recent version, with 16 px font size:
![image](https://user-images.githubusercontent.com/24237149/142480632-ffbd5514-1eb9-40f8-aebf-df0c9cb8df1d.png)

Here is the preview from Snowb bmf, the exported font has the same subpixel blur around each character as well.
![image](https://user-images.githubusercontent.com/24237149/142481197-96551715-4a25-4109-85c0-c2638bc30c9b.png)

Is there a setting I'm missing somewhere? Or could an option be added to disable font smoothing? Any/all info is greatly appreciated.

**Comment by SilenceLeo** [comment]
I added a sharpening function.

But there is currently a problem in Chrome. If the font size is too small (eg. 16px), the path rendering is not ideal. There is no such problem in Firefox.

I think this is a bug of canvas fill path in Chrome.

I will continue to improve the code. If you find any problems in use, please submit an issue.

Firefox screenshot:
![in Firefox](https://user-images.githubusercontent.com/4632034/143024788-0f3a2a64-267e-49a2-a39b-6e6d701e3044.png)

Chrome screenshot:
![in Chrome](https://user-images.githubusercontent.com/4632034/143025058-a7e0b7e0-2175-4ef0-af2d-a88bca4c88a0.png)
