### ISSUE TITLE
Small font sizes no longer rendering correctly?

### ISSUE THREAD

**Issue by Silver-Streak** [SilenceLeo/snowb-bmf#38]
It has been a few months since I last exported a new bitmap font.

While previously I had issues with font being blurry, which you fixed with the sharpening option, now I'm seeing issues where fonts aren't rendered properly due to being cut off and slightly transparent.

Here is what this font looked like a few months back when you did the sharpening fix: 
![image](https://user-images.githubusercontent.com/24237149/165309944-9e7a8ca5-6021-4c9c-9bc6-8a2b5f0e01bd.png)

Here is what it looks today with the same settings, no matter which browser I use:
![image](https://user-images.githubusercontent.com/24237149/165310126-4bb6579c-7200-4263-9a49-ca98deaa752d.png)

For some reason, parts of the fonts are now transparent, and many characters are cut off. Is there a new setting I'm missing or something that broke in the interim? The font can be obtained from here for testing: https://datagoblin.itch.io/monogram

**Comment by SilenceLeo** [comment]
Hi,

Do you have this problem using Firefox?

**Comment by Silver-Streak** [comment]
Good call.  Firefox does render correctly. 
![image](https://user-images.githubusercontent.com/24237149/165432090-f48032fa-d7a0-493e-9776-5f2297c76c79.png)
