### ISSUE TITLE
File Open Bug and Sharp Setting defaulting to value Bug

### ISSUE THREAD

**Issue by Superneutrino** [SilenceLeo/snowb-bmf#40]
Noticed in Firefox 100.0 

**File Open:**
When done working on font file, Editor can't open another font saved font. Had to refresh the page to Open it.

**Defaulting Bug:**
Sharp Setting defaults to 80% on save. Editor opens font with 80% Sharp as default. *decimal values in fnt file may cause some game engines not to render fonts correctly.

**Comment by SilenceLeo** [comment]
File Open: 
I can't reproduce this problem. Can you describe it in detail?

**Comment by MikelVazquez** [comment]
Same happening here.

You open a new file and in the moment you touch anything, for example, change padding from 1 to 2, you can't open a file anymore

**Comment by MikelVazquez** [comment]
Nope, a new file, touch anything and then you could not open a saved one.

BUT, I was testing it now and now it's working fine, it opens the saved file every time, not sure if you have changed something.

**Comment by SilenceLeo** [comment]
@MikelVazquez 
Yes, I added logic to reset after selecting a file.  https://github.com/SilenceLeo/snowb-bmf/commit/df4143ebc9e090d988f3e5d7b3c2155feec355b5

Thank you so much for your positive test. 🤝

**Comment by MikelVazquez** [comment]
Awesome! Thanks to you for your tool! :)
