### ISSUE TITLE
how to rename font when export? 

### ISSUE THREAD

**Issue by finscn** [SilenceLeo/snowb-bmf#53]
how to rename font ?  I can't find the input-box or text-area for edit font name

**Comment by finscn** [comment]
我还是说中文吧。
我的意思是导出字体时 指定字体名称。
同一个sbf文件，导出不同的字体名。
比如 描边和不描边的，我不想创建两个sbf文件。

**Comment by SilenceLeo** [comment]
目前还真不能这么弄，我可以加一下。
如果着急用的话，只能手动修改导出的文件了。
