### ISSUE TITLE
ttf or otf export

### ISSUE THREAD

**Issue by berkayk** [SilenceLeo/snowb-bmf#61]
Is it possible to convert the output files to ttf or otf?

**Comment by SilenceLeo** [comment]
https://github.com/SilenceLeo/snowb-bmf/issues/61


I think this tool is what you want.
https://www.fontsquirrel.com/tools/webfont-generator

**Comment by SilenceLeo** [comment]
https://github.com/SilenceLeo/snowb-bmf/discussions/60


I think this tool is what you want.
https://www.fontsquirrel.com/tools/webfont-generator
