### ISSUE TITLE
Support For kerning Pairs?

### ISSUE THREAD

**Issue by olivergamevy** [SilenceLeo/snowb-bmf#69]
It would be good to support kerning pairs so certain characters are displayed as AV and not  A V
![image](https://user-images.githubusercontent.com/14982298/234069658-2694ca14-0b20-4782-a55e-e49f884848bd.png)

**Comment by SilenceLeo** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/4632034/234575591-22cc6450-93a9-48dd-9490-af6592a99e39.png">
