### ISSUE TITLE
Part with low alpha are not detected properly

### ISSUE THREAD

**Issue by MikelVazquez** [SilenceLeo/snowb-bmf#70]
I'm creating 2 fonts where one it's going to be the shadow of the one on top, so to have perfect control on both I'm creating an area bigger than the letters with alpha = 0.01, but the program is cutting those parts off.

I'm using Chome Version 113.0.5672.127 (Official Build) (64-bit)
Same happens in Firefox

Really great program BTW! Thanks for doing it!

![image](https://github.com/SilenceLeo/snowb-bmf/assets/32359950/8c5e6e66-7b30-4cbe-8a89-3dd914a7aeec)

**Comment by SilenceLeo** [comment]
Yes, the current default threshold for alpha trim is 0.039 (10/255), so 0.01 will be trimmed.
I will set it to 0 to meet your requirements.


https://github.com/SilenceLeo/snowb-bmf/blob/f08527a14e7ea30739377ffe892c3444bacf5375/src/utils/getTrimImageInfo.ts#L9

**Comment by MikelVazquez** [comment]
Thanks a lot!!! ❤️

**Comment by MikelVazquez** [comment]
Hi Leo!
Sorry to bother you but the problem persists. Do I need to do something in a different way?
![image](https://github.com/SilenceLeo/snowb-bmf/assets/32359950/83054245-4002-4309-b755-92db2988e905)

**Comment by SilenceLeo** [comment]
@MikelVazquez 
Please send the original image so that I can debug it more easily.

**Comment by SilenceLeo** [comment]
It's a PWA caching issue. You can resolve it by forcibly deleting the old application in the browser's developer tools.

I will investigate and fix the application update problem.

<img width="627" alt="image" src="https://github.com/SilenceLeo/snowb-bmf/assets/4632034/eedeae18-ea3a-4da5-a7bb-d714d05a8bff">

**Comment by MikelVazquez** [comment]
Awesome! I did that and now I can see that it's working. Thanks a lot Leo, you are a star :)
