### ISSUE TITLE
Can't install & build

### ISSUE THREAD

**Issue by finscn** [SilenceLeo/snowb-bmf#71]
when I run `npm install`, get some error messages: 
<img width="717" alt="image" src="https://github.com/SilenceLeo/snowb-bmf/assets/288367/edd0e5c3-d30b-4d3a-9a3b-d82aeb2812d3">

**Comment by finscn** [comment]
I've used 'npm install --force' to finish install. but there are many warnings & `deprecated`.
So I think maybe it's time to upgrade the version of  packages in `dependencies` & `devDependencies`

**Comment by SilenceLeo** [comment]
好的，安排。

**Comment by SilenceLeo** [comment]
Try again.

**Comment by SilenceLeo** [comment]
I use `YARN` for package management in the project. If you use `npm`, you won't be able to use the correct package versions locked in `yarn.lock`, which can lead to issues like version mismatch.
