### ISSUE TITLE
请问导出后的字体宽度是不一致的

### ISSUE THREAD

**Issue by WenMoo** [SilenceLeo/snowb-bmf#81]
导入的图片数字“1”和数字“2”，图片的宽度都是相同的，但是生成的字体，在使用发现，1 的约束框 26，2的约束框是 28

**Comment by WenMoo** [comment]
感觉是把图片的透明区给剪裁了，导致宽度不对了，请问是我这设置有问题吗？

**Comment by SilenceLeo** [comment]
默认优化图片大小会裁剪空白，但是会有xoffset width xadvance等信息标记原字形宽度，算下来之后应该是正确的。
