### ISSUE TITLE
Missing Ability to Rename Glyph

### ISSUE THREAD

**Issue by Vincent-Maximon** [SilenceLeo/snowb-bmf#82]
Allow me renaming the glyph right in the editor will make it able to import some image as window doesn't allow some special character.

**Previously i remembered that the tool allow me to renaming the glyph as will
![image](https://github.com/SilenceLeo/snowb-bmf/assets/99956275/9eddcefa-f91d-4d22-a9df-64e09e5f56a7)

**Comment by SilenceLeo** [comment]
I apologize for the oversight, as I missed this during the recent UI library upgrade. 

Thank you for bringing it to my attention, and I have now fixed this issue.

**Comment by SilenceLeo** [comment]
> 

It should be a CDN caching issue, and I am currently trying to make the cache invalid.

**Comment by SilenceLeo** [comment]
> <img alt="Screenshot 2023-08-09 at 19 45 22" width="485" src="https://user-images.githubusercontent.com/99956275/259410291-50714ebc-1979-4130-bf16-4d4c8f192dc1.png"> Still don't have the ability to rename the glyph.

It should be a CDN caching issue, and I am currently trying to make the cache invalid.

**Comment by SilenceLeo** [comment]
![image](https://github.com/SilenceLeo/snowb-bmf/assets/4632034/1ccb214f-52d4-408d-ba7b-6b61b3bc1e7d)
I have accessed the latest version.
