### ISSUE TITLE
Global Metric Adjustments not working anymore

### ISSUE THREAD

**Issue by MikelVazquez** [SilenceLeo/snowb-bmf#83]
Nothing happens now when you change the values of this parameters :S

![image](https://github.com/SilenceLeo/snowb-bmf/assets/32359950/e4379be5-21f3-44b1-aa50-ca58ed5d751e)

**Comment by SilenceLeo** [comment]
Now, you can see the changes in real-time in the preview interface.

**Comment by SilenceLeo** [comment]
From the comparison between the preview and exported files, it seems like the configuration is working fine. Are you referring to the inability to preview in real-time?


<img width="1291" alt="image" src="https://github.com/SilenceLeo/snowb-bmf/assets/4632034/e0fa797c-befc-477f-8b4d-df7bb3513ead">

![image](https://github.com/SilenceLeo/snowb-bmf/assets/4632034/fb268787-1b66-477d-a2de-098cf6d3a68d)

**Comment by MikelVazquez** [comment]
I don't know what happened, but yesterday changing those values was not doing anything in the preview, but I have reloaded the font I saved and now it's working. 

I'm going to check one thing just in case

**Comment by MikelVazquez** [comment]
I was testing to redo it from scratch in case it was something that happened when first loading the web, but no... it's working fine today 🤷‍♂️  Sorry and thanks Leo!
