### ISSUE TITLE
Kerning amount between chars not working

### ISSUE THREAD

**Issue by MikelVazquez** [SilenceLeo/snowb-bmf#85]
Hi Leo! Sorry to bother you again, but I have found this issue.

https://github.com/SilenceLeo/snowb-bmf/assets/32359950/85957a8b-2be8-4b5b-a79c-b1f3045b0bf6

Thank you so much for your work!

**Comment by SilenceLeo** [comment]
The real-time preview issue has been fixed.

**Comment by MikelVazquez** [comment]
Thanks a lot for all this work Leo! Really appreciated
