### ISSUE TITLE
Line Height value it's not loaded right when you load the .sbf file

### ISSUE THREAD

**Issue by MikelVazquez** [SilenceLeo/snowb-bmf#87]
You save the file with this values
![image](https://github.com/SilenceLeo/snowb-bmf/assets/32359950/424ccfb6-ee71-4f52-88f3-e0610250bb23)

but when you load the file you have this
![image](https://github.com/SilenceLeo/snowb-bmf/assets/32359950/5c34593e-69ca-49e5-b1d1-fa449c2e9afe)

**Comment by SilenceLeo** [comment]
Hi @MikelVazquez,

Thank you for your feedback. I have fixed it, but you will need to re-edit and save the project. The old .sbf file has an error in the lineHeight data type.

**Comment by MikelVazquez** [comment]
Thanks a lot Leo! You are awesome :D
