### ISSUE TITLE
Longer symbols for currencies don't work properly anymore

### ISSUE THREAD

**Issue by mati187** [SilenceLeo/snowb-bmf#88]
I work with lots of different currencies when making bitmaps and they used to work fine until recently, now I get clipping and cuts on symbols, I'll attach a picture as example.

![example](https://github.com/SilenceLeo/snowb-bmf/assets/146319666/5e29966d-2f94-4065-9240-ef3892a3d71b)

Thank you for your work

**Comment by SilenceLeo** [comment]
Can you please provide your font file and character set?

**Comment by mati187** [comment]
Yes ofcourse. This also happens with any other font that I add those currencies. Anyways;

Font file (didn't let me upload directly here):
https://we.tl/t-68Gg20NjEm

Character Set:
0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ¡!№;%:¿?*()_+-=.,/|"'@#^&{}[]<>ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖÙÚÛÜÝßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿıŠšŸ⃀⃁⃂⃃⃄⃅⃆⃇⃈͸͹΀΁΃΋΍΢¢£¥µØÞŒœƒ₦₩€₱₲₹₺₽₾₿$

Thanks for the fast reply

**Comment by SilenceLeo** [comment]
Hi @mati187 ,

I have fixed this issue, please try again.

Thank you for feedback.

![image](https://github.com/SilenceLeo/snowb-bmf/assets/4632034/88c9c0c7-653f-4ad6-8def-c44d35da02a9)

**Comment by mati187** [comment]
Thank you so much!
