### ISSUE TITLE
Can't open early saved file .sbf

### ISSUE THREAD

**Issue by YuriiSemenuik** [SilenceLeo/snowb-bmf#89]
When I attempt to load a file, an error occurs, and the file does not load. This issue is not present with new project files; I can reopen and work with them without any problems. However, I am unable to do so with old ones.
![image](https://github.com/SilenceLeo/snowb-bmf/assets/1403499/739a87cb-4698-42ea-aa80-eb7f499440e2)
[paytable_1_font.zip](https://github.com/SilenceLeo/snowb-bmf/files/12754900/paytable_1_font.zip)

**Comment by SilenceLeo** [comment]
Hi @YuriiSemenuik @huachangmiao @DaNaoFu11 ,

I have fixed this issue, please try again.
