### ISSUE TITLE
老版本sbf不能使用

### ISSUE THREAD

**Issue by DaNaoFu11** [SilenceLeo/snowb-bmf#91]
作者你好，现在老版本的sbg不能使用，请问能否兼容老版本sbf或者能否告知如何部署这个网页

**Comment by SilenceLeo** [comment]
你好，能发一下你的sdf文件吗？我调试一下。

**Comment by huachangmiao** [comment]
[1common32.zip](https://github.com/SilenceLeo/snowb-bmf/files/12879590/1common32.zip)

**Comment by SilenceLeo** [comment]
Duplicate of #89
